spring:
  application:
    name: email-processing-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-processing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.email_listener_service.dto,com.example.email_processing_service.dto
        spring.json.value.default.type: com.example.email_processing_service.dto.EmailMessage

server:
  port: 8081
