spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: email-listener-service
  mail:
    host: imap.gmail.com
    port: 993
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        imap:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        store:
          protocol: imaps
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
