spring:
  config:
    import: optional:file:.env[.properties],optional:file:email-listener-service/.env[.properties]
  application:
    name: email-listener-service
  mail:
    host: ${EMAIL_IMAP_HOST:imap.gmail.com}
    port: ${EMAIL_IMAP_PORT:993}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        imap:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        store:
          protocol: imaps
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: 8082

app:
  kafka:
    topic:
      incoming: ${KAFKA_TOPIC_INCOMING:incoming-emails}
